spring:
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/selfsys?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
server:
  port: 9999