spring:
  datasource:
    url: jdbc:mysql://192.168.1.11:3306/selfsys?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root2
    password: root2

server:
  port: 9999

logging:
  level:
    top.heapoverflow.yunnote: debug
    org.springframework.web.client.RestTemplate: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.heapoverflow.yunnote
